FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
RUN apt-get install -y postgresql postgresql-contrib libpq-dev
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5000
EXPOSE 8091
ENTRYPOINT ["python"]
CMD ["geo_tracker/main.py"]
